<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Erdems-MacBook-Pro.local" failures="1" tests="5" name="Personal loan" time="0.03" errors="0" timestamp="15 Jun 2019 14:41:37 GMT">
  <testcase classname="test1.day1" name="Demo" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test1.day1.Demo(day1.java:22)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test1.day2" name="ploan" time="0.001"/>
  <testcase classname="test1.day4" name="LoginAPIHomeLoan" time="0.001"/>
  <testcase classname="test1.day4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="test1.day4" name="WebloginHomeLoan" time="0.001"/>
  <testcase classname="test1.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
